<a href="https://colab.research.google.com/github/thakur-works/aics-lab/blob/main/LInearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model 

In [5]:
data =pd.read_csv("Salary_Data.csv")
data

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [21]:
x=data.YearsExperience
y=data.Salary
x=np.array(x)
y=np.array(y)
print(type(x))
print(x)
x=x.reshape(-1,1)

<class 'numpy.ndarray'>
[ 1.1  1.3  1.5  2.   2.2  2.9  3.   3.2  3.2  3.7  3.9  4.   4.   4.1
  4.5  4.9  5.1  5.3  5.9  6.   6.8  7.1  7.9  8.2  8.7  9.   9.5  9.6
 10.3 10.5]


In [27]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
x_train=np.array(x_train).reshape(-1,1)
x_test=np.array(x_test).reshape(-1,1)
y_train=np.array(y_train)
y_test=np.array(y_test)

In [17]:
print(x_train.shape)
print(x_test.shape)

print(y_train.shape)
print(y_test.shape)
print(x_train)

(24, 1)
(6, 1)
(24,)
(6,)
[[ 9.5]
 [ 2. ]
 [ 8.7]
 [ 7.9]
 [ 8.2]
 [ 2.2]
 [ 1.5]
 [ 9. ]
 [ 3. ]
 [ 5.9]
 [ 4.1]
 [ 3.2]
 [ 9.6]
 [ 1.3]
 [ 5.1]
 [ 1.1]
 [ 4.9]
 [10.5]
 [10.3]
 [ 3.7]
 [ 3.2]
 [ 4. ]
 [ 4. ]
 [ 2.9]]


In [37]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score
# classifier_knn=KNeighborsClassifier(n_neighbors=9)
# classifier_knn.fit(x_train,y_train)
# y_pred=classifier_knn.predict(x_test)
# print(y_pred)
# print(y_test)
# print("Accuracy:",accuracy_score(y_test, y_pred))



[54445. 66029. 54445. 55794. 54445. 57081.]
[83088. 98273. 63218. 93940. 61111. 91738.]
Accuracy: 0.0


In [28]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)
#model=LinearRegression.fit(x,y)

LinearRegression()

In [29]:
r_sq = model.score(x, y)
print(f"coefficient of determination:{r_sq}")

coefficient of determination:0.9559200375146585


In [30]:
print(f"intercept: {model.intercept_}")
print(f"slope: {model.coef_}")


intercept: 25609.89799835482
slope: [9332.94473799]


In [31]:
y_pred = model.predict(x_test)

In [32]:
print(f"predicted response:\n{y_pred}")

predicted response:
[75074.50510972 91873.8056381  62008.38247653 81607.56642631
 67608.14931932 89073.92221671]


In [42]:
#from sklearn.metrics import accuracy_score
#from sklearn import regression
#print("Accuracy:",regression.accuracy_score(y_test, y_pred))

In [34]:
print(y_test)

[83088. 98273. 63218. 93940. 61111. 91738.]
